package com.xda.sa2ration.ui.calibration;

import android.content.res.Configuration;import android.os.Bundle;import android.widget.ArrayAdapter;import android.widget.LinearLayout;import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;import androidx.core.graphics.Insets;import androidx.core.view.ViewCompat;import androidx.core.view.WindowCompat;import androidx.core.view.WindowInsetsCompat;
import com.google.android.material.appbar.MaterialToolbar;import com.google.android.material.color.MaterialColors;import com.google.android.material.textfield.MaterialAutoCompleteTextView;import com.google.android.material.textfield.TextInputLayout;import com.xda.sa2ration.R;

public final class CalibrationActivity extends AppCompatActivity {
    @Override protected void onCreate(Bundle state){super.onCreate(state);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(MaterialColors.getColor(root,com.google.android.material.R.attr.colorSurface,0xfffafafa));MaterialToolbar toolbar=new MaterialToolbar(this);toolbar.setTitle(R.string.calibration_title);toolbar.setNavigationIcon(R.drawable.ic_arrow_back);toolbar.setNavigationOnClickListener(v->finish());toolbar.setMinimumHeight(dp(64));root.addView(toolbar,new LinearLayout.LayoutParams(-1,-2));LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);int padding=getResources().getDimensionPixelSize(R.dimen.screen_horizontal_padding);body.setPadding(padding,padding,padding,padding);TextView warning=new TextView(this);warning.setText(R.string.calibration_warning);warning.setTextSize(13);warning.setTextColor(MaterialColors.getColor(warning,com.google.android.material.R.attr.colorOnSurfaceVariant,0xff555555));body.addView(warning);CalibrationPatternView preview=new CalibrationPatternView(this);LinearLayout.LayoutParams previewParams=new LinearLayout.LayoutParams(-1,0,1);previewParams.setMargins(0,dp(12),0,dp(12));body.addView(preview,previewParams);String[]labels=getResources().getStringArray(R.array.calibration_patterns);TextInputLayout selector=new TextInputLayout(this,null,com.google.android.material.R.attr.textInputOutlinedStyle);selector.setHint(R.string.calibration_pattern);selector.setBoxBackgroundMode(TextInputLayout.BOX_BACKGROUND_OUTLINE);MaterialAutoCompleteTextView dropdown=new MaterialAutoCompleteTextView(selector.getContext());dropdown.setInputType(0);dropdown.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,labels));dropdown.setText(labels[0],false);dropdown.setOnItemClickListener((p,v,position,id)->preview.setPattern(CalibrationPattern.values()[position]));selector.addView(dropdown);body.addView(selector);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);int mode=getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK;boolean light=mode!=Configuration.UI_MODE_NIGHT_YES;WindowCompat.getInsetsController(getWindow(),root).setAppearanceLightStatusBars(light);WindowCompat.getInsetsController(getWindow(),root).setAppearanceLightNavigationBars(light);ViewCompat.setOnApplyWindowInsetsListener(root,(view,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.displayCutout());toolbar.setPadding(bars.left,bars.top,bars.right,0);body.setPadding(Math.max(padding,bars.left),padding,Math.max(padding,bars.right),Math.max(padding,bars.bottom));return insets;});ViewCompat.requestApplyInsets(root);}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
}
