package com.xda.sa2ration.automation;
public enum AutomationConditionType { APPLICATION, TIME_RANGE, DAY_OF_WEEK, SUNRISE, SUNSET, AMBIENT_LIGHT, BATTERY_LEVEL, CHARGING, POWER_SAVER, TEMPERATURE, ORIENTATION, EXTERNAL_DISPLAY, DESKTOP_MODE, GAME, VIDEO, HDR, CURRENT_BRIGHTNESS }
